# Generated by Django 3.2.5 on 2021-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='priority',
            field=models.CharField(max_length=20),
        ),
    ]
